language: python
python:
- '2.7'
- '3.3'
- pypy
script: python reconcile_test.py
env:
  global:
    secure: SJEQ30ExiK2aPuZsS3ErCitQX7MuKfhkPP4+7W0HgAMt5Oy2Mo4zLH7QDkp65pqDCPv8MeFCXwJYu1zqmLHksfL8hOrjtJOGMn5k30OfeFJLJji2E2NoZohJTQZqabe5Tgca2zC9CE+LiemEefOQywLWMXeEJ9N+h9R3BwaGYmA=
